// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PGSA_Licence3.Data;

#nullable disable

namespace PGSA_Licence3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251229162430_AddEtudiantGroupesRelation")]
    partial class AddEtudiantGroupesRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EtudiantGroupe", b =>
                {
                    b.Property<int>("EtudiantsId")
                        .HasColumnType("int");

                    b.Property<int>("GroupesId")
                        .HasColumnType("int");

                    b.HasKey("EtudiantsId", "GroupesId");

                    b.HasIndex("GroupesId");

                    b.ToTable("EtudiantGroupes", (string)null);
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Assiduite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnregistreurId")
                        .HasColumnType("int");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<double>("HeuresEffectuees")
                        .HasColumnType("double");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("StatutValidation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EnregistreurId");

                    b.HasIndex("SeanceId");

                    b.HasIndex("EtudiantId", "SeanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Assiduite_EtudiantId_SeanceId");

                    b.ToTable("Assiduites");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.CahierDeTexte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitesRealisees")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ObjectifsPedagogiques")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RessourcesUtilisees")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<string>("TravauxAFaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SeanceId")
                        .IsUnique();

                    b.ToTable("CahiersDeTexte");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Cours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeAcademique")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnseignantId")
                        .HasColumnType("int");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Semestre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("EnseignantId");

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Filiere")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Justification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheminDocument")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CommentaireValidation")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EtudiantId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ValidateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeanceId");

                    b.HasIndex("ValidateurId");

                    b.HasIndex("EtudiantId", "SeanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_Justification_EtudiantId_SeanceId");

                    b.ToTable("Justifications");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Niveau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomNiveau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Niveaux");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DestinataireId")
                        .HasColumnType("int");

                    b.Property<int?>("EntiteAssocieeId")
                        .HasColumnType("int");

                    b.Property<string>("LienAction")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("TypeEntiteAssociee")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Seance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateHeureDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateHeureFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Duree")
                        .HasColumnType("int");

                    b.Property<int?>("GroupeId")
                        .HasColumnType("int");

                    b.Property<int?>("NiveauId")
                        .HasColumnType("int");

                    b.Property<string>("Salle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SpecialiteId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("CycleId");

                    b.HasIndex("GroupeId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("SpecialiteId");

                    b.ToTable("Seances");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.SignalementAbsenceEnseignant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateSignalement")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DelegueId")
                        .HasColumnType("int");

                    b.Property<string>("Motif")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int?>("TraitantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DelegueId");

                    b.HasIndex("SeanceId")
                        .IsUnique()
                        .HasDatabaseName("IX_SignalementAbsenceEnseignant_SeanceId");

                    b.HasIndex("TraitantId");

                    b.ToTable("SignalementsAbsenceEnseignant");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Specialite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomSpecialite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specialites");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmailInstitutionnel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Matricule")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PGSA_Licence3.Models.ValidationSeance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateValidation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SeanceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TypeValidation")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ValidateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ValidateurId");

                    b.HasIndex("SeanceId", "ValidateurId", "TypeValidation")
                        .IsUnique()
                        .HasDatabaseName("IX_ValidationSeance_SeanceId_ValidateurId_TypeValidation");

                    b.ToTable("ValidationsSeance");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Enseignant", b =>
                {
                    b.HasBaseType("PGSA_Licence3.Models.User");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Specialite")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasDiscriminator().HasValue("Enseignant");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Etudiant", b =>
                {
                    b.HasBaseType("PGSA_Licence3.Models.User");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NiveauId")
                        .HasColumnType("int");

                    b.Property<int>("SpecialiteId")
                        .HasColumnType("int");

                    b.HasIndex("CycleId");

                    b.HasIndex("NiveauId");

                    b.HasIndex("SpecialiteId");

                    b.HasDiscriminator().HasValue("Etudiant");
                });

            modelBuilder.Entity("EtudiantGroupe", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Etudiant", null)
                        .WithMany()
                        .HasForeignKey("EtudiantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Groupe", null)
                        .WithMany()
                        .HasForeignKey("GroupesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Assiduite", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.User", "Enregistreur")
                        .WithMany()
                        .HasForeignKey("EnregistreurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Seance", "Seance")
                        .WithMany("Assiduites")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enregistreur");

                    b.Navigation("Etudiant");

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.CahierDeTexte", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Seance", "Seance")
                        .WithOne("CahierDeTexte")
                        .HasForeignKey("PGSA_Licence3.Models.CahierDeTexte", "SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seance");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Cours", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Enseignant", "Enseignant")
                        .WithMany("Cours")
                        .HasForeignKey("EnseignantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enseignant");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Justification", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Etudiant", "Etudiant")
                        .WithMany()
                        .HasForeignKey("EtudiantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Seance", "Seance")
                        .WithMany()
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.User", "Validateur")
                        .WithMany()
                        .HasForeignKey("ValidateurId");

                    b.Navigation("Etudiant");

                    b.Navigation("Seance");

                    b.Navigation("Validateur");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Notification", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.User", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinataire");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Seance", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Cours", "Cours")
                        .WithMany("Seances")
                        .HasForeignKey("CoursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId");

                    b.HasOne("PGSA_Licence3.Models.Groupe", "Groupe")
                        .WithMany("Seances")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PGSA_Licence3.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("NiveauId");

                    b.HasOne("PGSA_Licence3.Models.Specialite", "Specialite")
                        .WithMany()
                        .HasForeignKey("SpecialiteId");

                    b.Navigation("Cours");

                    b.Navigation("Cycle");

                    b.Navigation("Groupe");

                    b.Navigation("Niveau");

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.SignalementAbsenceEnseignant", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.User", "Delegue")
                        .WithMany()
                        .HasForeignKey("DelegueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Seance", "Seance")
                        .WithMany()
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.User", "Traitant")
                        .WithMany()
                        .HasForeignKey("TraitantId");

                    b.Navigation("Delegue");

                    b.Navigation("Seance");

                    b.Navigation("Traitant");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.ValidationSeance", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Seance", "Seance")
                        .WithMany("Validations")
                        .HasForeignKey("SeanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.User", "Validateur")
                        .WithMany()
                        .HasForeignKey("ValidateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seance");

                    b.Navigation("Validateur");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Etudiant", b =>
                {
                    b.HasOne("PGSA_Licence3.Models.Cycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Niveau", "Niveau")
                        .WithMany()
                        .HasForeignKey("NiveauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PGSA_Licence3.Models.Specialite", "Specialite")
                        .WithMany()
                        .HasForeignKey("SpecialiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("Niveau");

                    b.Navigation("Specialite");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Cours", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Groupe", b =>
                {
                    b.Navigation("Seances");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Seance", b =>
                {
                    b.Navigation("Assiduites");

                    b.Navigation("CahierDeTexte");

                    b.Navigation("Validations");
                });

            modelBuilder.Entity("PGSA_Licence3.Models.Enseignant", b =>
                {
                    b.Navigation("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
